#include "../src/layer/input/input.h"
#include "../src/layer/activation/relu.h"
#include "../src/layer/conv/conv2d.h"
#include "../src/layer/pooling/maxpool2d.h"
#include "../src/layer/upsampling/upsample2d.h"
